# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Tag.create(nome: "algebra lineare");
Tag.create(nome: "analisi di mercato");
Tag.create(nome: "antropologia");
Tag.create(nome: "archeologia");
Tag.create(nome: "architettura");
Tag.create(nome: "arte moderna");
Tag.create(nome: "arte preistorica");
Tag.create(nome: "astrattismo");
Tag.create(nome: "astrofisica");
Tag.create(nome: "astronomia");
Tag.create(nome: "automatica");
Tag.create(nome: "basi di dati");
Tag.create(nome: "biologia");
Tag.create(nome: "biologia molecolare");
Tag.create(nome: "biotecnologie");
Tag.create(nome: "calcolo combinatorio");
Tag.create(nome: "calcolo delle probabilità");
Tag.create(nome: "calcolo differenziale");
Tag.create(nome: "chimica");
Tag.create(nome: "chimica inorganica");
Tag.create(nome: "chimica organica");
Tag.create(nome: "chirurgia estetica");
Tag.create(nome: "cinema e media");
Tag.create(nome: "corone fiorentine");
Tag.create(nome: "cosmologia");
Tag.create(nome: "criminologia");
Tag.create(nome: "cucina");
Tag.create(nome: "diritto civile");
Tag.create(nome: "diritto commerciale");
Tag.create(nome: "diritto internazionale");
Tag.create(nome: "diritto penale");
Tag.create(nome: "diritto romano");
Tag.create(nome: "duemila");
Tag.create(nome: "economia internazionale");
Tag.create(nome: "economia politica");
Tag.create(nome: "educazione civica");
Tag.create(nome: "elettromagnetismo");
Tag.create(nome: "elettronica");
Tag.create(nome: "elettrotecnica");
Tag.create(nome: "epica");
Tag.create(nome: "etica");
Tag.create(nome: "farmacologia");
Tag.create(nome: "filosofia antica");
Tag.create(nome: "filosofia contemporanea");
Tag.create(nome: "filosofia cristiana");
Tag.create(nome: "filosofia medievale");
Tag.create(nome: "filosofia moderna");
Tag.create(nome: "fisiologia animale");
Tag.create(nome: "fisiologia umana");
Tag.create(nome: "fisiologia vegetale");
Tag.create(nome: "fluidodinamica");
Tag.create(nome: "genetica");
Tag.create(nome: "geologia");
Tag.create(nome: "geometria analitica");
Tag.create(nome: "geometria euclidea");
Tag.create(nome: "geometria solida");
Tag.create(nome: "giurisprudenza");
Tag.create(nome: "immunologia");
Tag.create(nome: "informatica teorica");
Tag.create(nome: "ingegneria aerospaziale");
Tag.create(nome: "ingegneria ambientale");
Tag.create(nome: "ingegneria biomedica");
Tag.create(nome: "ingegneria chimica");
Tag.create(nome: "ingegneria civile");
Tag.create(nome: "ingegneria delle telecomunicazioni");
Tag.create(nome: "ingegneria elettronica");
Tag.create(nome: "ingegneria energetica");
Tag.create(nome: "ingegneria informatica");
Tag.create(nome: "ingegneria meccanica");
Tag.create(nome: "intelligenza artificiale");
Tag.create(nome: "letteratura europea");
Tag.create(nome: "letteratura moderna");
Tag.create(nome: "letteratura orientale");
Tag.create(nome: "lettere classiche");
Tag.create(nome: "lingua cinese");
Tag.create(nome: "lingua francese");
Tag.create(nome: "lingua giapponese");
Tag.create(nome: "lingua greca");
Tag.create(nome: "lingua inglese");
Tag.create(nome: "lingua latina");
Tag.create(nome: "lingua russa");
Tag.create(nome: "lingua spagnola");
Tag.create(nome: "logica");
Tag.create(nome: "macroeconomia");
Tag.create(nome: "management and business administration");
Tag.create(nome: "marketing");
Tag.create(nome: "matematica finanziaria");
Tag.create(nome: "matematica");
Tag.create(nome: "meccanica");
Tag.create(nome: "medicina");
Tag.create(nome: "medioevo");
Tag.create(nome: "microbiologia");
Tag.create(nome: "microeconomia");
Tag.create(nome: "narrativa");
Tag.create(nome: "novecento");
Tag.create(nome: "organizzazione aziendale");
Tag.create(nome: "pedagogia");
Tag.create(nome: "poesia");
Tag.create(nome: "politiche globali");
Tag.create(nome: "politiche sociali");
Tag.create(nome: "progettazione di siti web");
Tag.create(nome: "progettazione uml");
Tag.create(nome: "programmazione assembly");
Tag.create(nome: "programmazione c");
Tag.create(nome: "programmazione java");
Tag.create(nome: "programmazione python");
Tag.create(nome: "prosa");
Tag.create(nome: "psicologia");
Tag.create(nome: "relazioni internazionali");
Tag.create(nome: "rinascimento");
Tag.create(nome: "risorgimento");
Tag.create(nome: "robotica e automazione");
Tag.create(nome: "saggio breve");
Tag.create(nome: "saggio critico");
Tag.create(nome: "saggio filosofico");
Tag.create(nome: "scienze infermieristiche");
Tag.create(nome: "scienze motorie");
Tag.create(nome: "scienze politiche");
Tag.create(nome: "scienze sociali");
Tag.create(nome: "scienze umanistiche");
Tag.create(nome: "sicurezza informatica");
Tag.create(nome: "simplesso");
Tag.create(nome: "sistemi informatici");
Tag.create(nome: "sociologia");
Tag.create(nome: "statistica");
Tag.create(nome: "storia antica");
Tag.create(nome: "storia contemporanea");
Tag.create(nome: "storia dell'arte");
Tag.create(nome: "storia greca");
Tag.create(nome: "storia moderna");
Tag.create(nome: "storia romana");
Tag.create(nome: "sviluppo software");
Tag.create(nome: "tecnologia e innovazione");
Tag.create(nome: "telecomunicazioni");
Tag.create(nome: "teologia");
Tag.create(nome: "termodinamica");
Tag.create(nome: "trigonometria");